# -*- coding: utf-8 -*-
"""BIRDS CUDA Cohort Week 2 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzAz7R7i17fgArgQj3WaEpM3ZVZYY1jq

**Q1. Create a simple Python script that starts two threads; each thread should print numbers from 1 to 5 with a delay of 1 second between each number.**
"""



"""**Q2. Write a Python program where two threads print alternating messages like "Ping" and "Pong" respectively.**"""



"""**Q3. Write a Python program using threads where a semaphore is used to limit access to a shared resource. For example, simulate a scenario where only a certain number of threads can write to a shared file at the same time. But feel free to choose any setting.**

P.S. You can just copy-paste from the colab we used in the Session. But make sure you understand it!
"""



"""**Q4. [OPTIONAL] Write a simple usecase of Mutex in C++. No need to run just dump the code in multiline comment below.**

[C++ CODE GOES HERE]

**Q5. [OPTIONAL] DINING PHILOSOPHER'S PROBLEM**

* There are five philosophers sitting around a dining table.
* Each philosopher thinks and eats spaghetti.
* To eat, a philosopher must have two forks (one on the left and one on the right).
* There is a single fork between each pair of adjacent philosophers.
* Philosophers must pick up both forks to eat and put them down when they're done.
"""

